name = "GnuPlotScripting"
uuid = "483a2fc8-eb99-45b6-a231-8c481e9ade22"
authors = ["Vincent Picaud"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
